#! /bin/bash

# Script to (re)generate most of the wrench images.
# Requires imagemagick.
#
# Base images needed:
#	- wrench_master_diagonal.png
#	- wrench_master_horizontal.png
# Both in grayscale colors.
#

materials="
	wood	#6C4913 100
	steel	#FFFFFF	130
	copper	#F6A860	100
	gold	#FFe900	130
	"

echo "$materials" \
| while read material color tint; do
    if [ -z "$material" ]; then continue; fi
    convert wrench_master_diagonal.png -fill "$color" -tint "$tint" -bordercolor none -border 1 "wrench_${material}.png"
    convert wrench_master_horizontal.png -fill "$color" -tint "$tint" -bordercolor none -border 1 "wrench_${material}_left.png"
    convert "wrench_${material}.png" -rotate -90 "wrench_${material}_cw.png"
    convert "wrench_${material}_cw.png" -flop "wrench_${material}_ccw.png"
    convert "wrench_${material}_left.png" -flop "wrench_${material}_right.png"
    convert "wrench_${material}_left.png" -rotate -90 "wrench_${material}_down.png"
    convert "wrench_${material}_right.png" -rotate -90 "wrench_${material}_up.png"
done

b=8
l=200
for axismode in 0 1 2 3 4 5; do
    convert \
	-size 18x18 \
	-matte \
	"xc:RGBA(0,0,0,0)" \
	-fill "RGB($b,$b,$b)" \
	-draw "line 15,1 15,6" \
	-fill "RGB($l,$b,$b)" \
	-draw "point 15,$((axismode + 1))" \
	"wrench_axismode_${axismode}.png"
done
for rotmode in 0 1 2 3 4 5; do
    convert \
	-size 18x18 \
	-matte \
	"xc:RGBA(0,0,0,0)" \
	-fill "RGB($b,$b,$b)" \
	-draw "line 16,1 16,4" \
	-fill "RGB($l,$b,$b)" \
	-draw "point 16,$((rotmode + 1))" \
	"wrench_rotmode_${rotmode}.png"
done
